experiment_parameters1 = [
    {
        "population_size": 1000,
        "mutation_rate": 0.2,
        "mutation_strength": 10,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 10,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.05,
        "mutation_strength": 10,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 2,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.4,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.2,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 20,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 40,
    },
    {
        "population_size": 2000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 500,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 30,
        "tournament_size": 30,
    },
    {
        "population_size": 1000,
        "mutation_rate": 0.1,
        "mutation_strength": 5,
        "crossover_rate": 0.3,
        "num_generations": 21,
        "tournament_size": 30,
    },
]
